# File: docker-compose.yml
# Path: fanfix-api/docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fanfix_db
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: pgvector/pgvector:pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./migrations/0001_initial.sql:/docker-entrypoint-initdb.d/0001_initial.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fanfix_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: